### ISSUE TITLE
Chrome locks database, copy operation fails, causes crash

### ISSUE THREAD

**Issue by ifconfig2333** [henryreed/chrome_enum#4]
Program will not fail as a result of a database lock by Chrome; i.e., you may launch this program while Chrome is running

.

Dumping cookies...
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Chrome-Cookies-Decryptor-Backbone-main\script.py", line 349, in <module>
    cookies = c.cookies()
              ^^^^^^^^^^^
  File "C:\Users\User\Downloads\Chrome-Cookies-Decryptor-Backbone-main\script.py", line 301, in cookies
    return {cookies_file: self.__individual_cookies(cookies_file, cookies_dir_and_key[cookies_file])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\Chrome-Cookies-Decryptor-Backbone-main\script.py", line 301, in <dictcomp>
    return {cookies_file: self.__individual_cookies(cookies_file, cookies_dir_and_key[cookies_file])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\Chrome1\script.py", line 314, in __individual_cookies
    shutil.copy2(database_file, filename)  # Copying to avoid lock issues
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\User\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'

Cookies cannot be read when Google Chrome is running
Cookies file is occupied. Cannot perform any operation.

**Comment by henryreed** [comment]
Seems to be an issue that came up with a newer version of Chrome. Thanks for reporting this, will look into it in the coming weeks.
